### ISSUE TITLE
automate / allow using a tunnel or port-forward for prometheus endpoint

### ISSUE THREAD

**Issue by strowi** [eslam-gomaa/kptop#11]
Hi,

neat tool;) 
Have you thought about automating and allowing to use a port-forward or tunnel to the (not-exposed) prometheus-service?

That would ease multi-cluster usage. Allowing to do sth. like export `KPTOP_PROMETHEUS_SERVER="http://127.0.0.1:8080` once and just use the current kubectl-context to create the tunnel etc without any more manual steps?

regards,
strowi

**Comment by eslam-gomaa** [comment]
Hi @strowi , Nice idea!

I'll try it later with Kubernetes apis and get back to you

**Comment by eslam-gomaa** [comment]
Feature added
#33
